language: go

go:
  - 1.6
  - 1.7

env:
  global:
    - secure: "rMvn3pYBCTD9QL7y5YTR4qTS935Yg/XTYV590Jc4WmI1ohniCjamqrF06eHIduBmnwt+OpvcKB54CLNqa2CbBJhV9rwXcWQ1w7ggvukx8V+VKXSgUSv6lLbXN7ZdQyUwpfsWnYVM6o+CT8OHr71FsAqMh3dMjSv3FYjdsKVfUXTRnxjXe+zscjxWRpn/CsbQ7PayPGnc8+c3/tULqayFekbI0Vax/OtbAMSlNkKUSDMCEc6JatJ3MYW0qWTZA59ECicpWFyF0xDwhYgAaj7t5dPLyWSJTdwebcixen7scdjQ8PiGa3mLs/NhK0Typ6CFHBuyHE4P50bAiekivTrwSdxpe6xGcEwY8ph/N2BKu6V0tjh/3rr+fnmfmu0SMNssDGLkQkK7THKMmFl9gkcIL+pRdee8xJbVCHwCbgsY9S12lu6MNwLwmV+iQ+QqEtVMJhEkpQE7sg3qSXYcMWpZC+r9cl1QHbEC1HvNO+k+tjgtGKpmE+hqAQI2reLg2HuzFBoxXTVDuvhf3bVL+U0R2fHfo2PiqFBUlAqBJfJPW1G4oP5YwWEtWoBWVNJXPUK4vGlFGH6jMcIqXxGfcQRO2NnfmpljOdgEgw2+xRV4Wi7Nacr+f7y1JupRS7mb8ZY9iuIKmyMdHmCamaEobijh+TBRLV8bHwmCJcRQIc/FPMM="
    - PACKAGE_VERSION: 0.0.17
    - REPO_NAME: shingetsu-gou
    - CGO_ENABLED:1 

gobuild_args: -ldflags "-X cfg.VERSION= ${PACKAGE_VERSION}"

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y automake autogen build-essential ca-certificates     gcc-arm-linux-gnueabi g++-arm-linux-gnueabi libc6-dev-armel-cross  gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf libc6-dev-armhf-cross  gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross  gcc-multilib g++-multilib gcc-mingw-w64 g++-mingw-w64 clang llvm-dev  libtool libxml2-dev uuid-dev libssl-dev swig pkg-config patch  make xz-utils cpio wget zip unzip p7zip  bzr texinfo help2man       --no-install-recommends
- go get github.com/axw/gocov/gocov
- go get github.com/alecthomas/gometalinter
- go get github.com/mattn/goveralls
- go get -u github.com/jteeuwen/go-bindata/...
- if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
- export PATH=$PATH:$GOPATH/bin
- gometalinter --install --update
- go-bindata -o util/bindata.go -pkg util www/... file/... gou_template/...

script:
- go test -v -covermode=count -coverprofile=coverage.out
#- ! gometalinter --deadline=1000s ./... 2>&1 | read

after_script:
- goveralls -coverprofile=coverage.out -service=travis-ci
- gometalinter -e bindata --deadline=1000s ./...
- if  [ ${TRAVIS_GO_VERSION} == "1.7" ]; then
  echo "Bootstrapping linux/amd64...";
  go build -o ${REPO_NAME}_linux_amd64;
  echo "Bootstrapping linux/386...";
  GOOS=linux GOARCH=386 go build -o ${REPO_NAME}_${PACKAGE_VERSION}_linux_386;
  echo "Bootstrapping linux/arm64...";
  GOOS=linux GOARCH=arm64  CC=aarch64-linux-gnu-gcc go build -o ${REPO_NAME}_${PACKAGE_VERSION}_linux_arm64;
  echo "Bootstrapping windows/amd64...";
  GOOS=windows GOARCH=amd64  CC=x86_64-w64-mingw32-gcc go build -o ${REPO_NAME}_${PACKAGE_VERSION}_win_amd64.exe;
  echo "Bootstrapping windows/386...";
  GOOS=windows GOARCH=386 CC=i686-w64-mingw32-gcc go build -o ${REPO_NAME}_${PACKAGE_VERSION}_win_386.exe;
  echo "Bootstrapping darwin/amd64...";
  GOOS=darwin GOARCH=amd64 CC=o64-clang go build -o ${REPO_NAME}_${PACKAGE_VERSION}_darwin_amd64;
  echo "Bootstrapping darwin/386...";
  GOOS=darwin GOARCH=386  CC=o32-clang go build -o ${REPO_NAME}_${PACKAGE_VERSION}_darwin_386;
  gzip ${REPO_NAME}_${PACKAGE_VERSION}_linux_386;
  gzip ${REPO_NAME}_${PACKAGE_VERSION}_linux_amd64;
  gzip ${REPO_NAME}_${PACKAGE_VERSION}_linux_arm64;
  zip ${REPO_NAME}_${PACKAGE_VERSION}_win_amd64.exe.zip  ${REPO_NAME}_${PACKAGE_VERSION}_win_amd64.exe;
  zip ${REPO_NAME}_${PACKAGE_VERSION}_win_386.exe.zip  ${REPO_NAME}_${PACKAGE_VERSION}_win_386.exe;
  zip ${REPO_NAME}_${PACKAGE_VERSION}_darwin_amd64.zip  ${REPO_NAME}_${PACKAGE_VERSION}_darwin_amd64;
  zip ${REPO_NAME}_${PACKAGE_VERSION}_darwin_386.zip  ${REPO_NAME}_${PACKAGE_VERSION}_darwin_386;
  cd ..;
  fi

deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TOKEN}
  file:
     -  "${REPO_NAME}_linux_386.gz"
     -  "${REPO_NAME}_linux_amd64.gz"
     -  "${REPO_NAME}_linux_arm64.gz"
     -  "${REPO_NAME}_win_386.exe.zip"
     -  "${REPO_NAME}_win_amd64.exe.zip"
     -  "${REPO_NAME}_darwin_386.zip"
     -  "${REPO_NAME}_darwin_amd64.zip"
  skip_cleanup: true
  on:
    repo: $REPO_NAME/$REPO_NAME
    tags: true
    all_branches: true
